//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GGKService.Common.Classes.GZKRequestResponse
{
    using System.Xml.Serialization;

    // 
    // This source code was auto-generated by xsd, Version=4.0.30319.33440.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://aisgzk.kz/integrations/v2019")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://aisgzk.kz/integrations/v2019", IsNullable = true)]
    public partial class GIDataResponse
    {

        private string pushIdField;

        private string layerNameField;

        private long dataCountField;

        private GIStructureInfo[] dataStructureField;

        /// <remarks/>
        public string PushId
        {
            get
            {
                return this.pushIdField;
            }
            set
            {
                this.pushIdField = value;
            }
        }

        /// <remarks/>
        public string LayerName
        {
            get
            {
                return this.layerNameField;
            }
            set
            {
                this.layerNameField = value;
            }
        }

        /// <remarks/>
        public long DataCount
        {
            get
            {
                return this.dataCountField;
            }
            set
            {
                this.dataCountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DataStructure")]
        public GIStructureInfo[] DataStructure
        {
            get
            {
                return this.dataStructureField;
            }
            set
            {
                this.dataStructureField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://aisgzk.kz/integrations/v2019")]
    public partial class GIStructureInfo : AnyDictionary
    {

        private GIStructureElementType typeField;

        private int sizeField;

        /// <remarks/>
        public GIStructureElementType Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        public int Size
        {
            get
            {
                return this.sizeField;
            }
            set
            {
                this.sizeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://aisgzk.kz/integrations/v2019")]
    public enum GIStructureElementType
    {

        /// <remarks/>
        unknown,

        /// <remarks/>
        text,

        /// <remarks/>
        number,

        /// <remarks/>
        datetime,
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ObjectPart))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Right))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Soil))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EconomicChar))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GIRelevanceInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GIStructureInfo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://aisgzk.kz/integrations/v2019")]
    public partial class AnyDictionary
    {

        private string codeField;

        private MLText nameField;

        /// <remarks/>
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        public MLText Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://aisgzk.kz/integrations/v2019")]
    public partial class MLText
    {

        private string ruField;

        private string kzField;

        /// <remarks/>
        public string Ru
        {
            get
            {
                return this.ruField;
            }
            set
            {
                this.ruField = value;
            }
        }

        /// <remarks/>
        public string Kz
        {
            get
            {
                return this.kzField;
            }
            set
            {
                this.kzField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://aisgzk.kz/integrations/v2019")]
    public partial class CadNumberHistory
    {

        private string cadNumberField;

        private MLText changeNameField;

        private System.DateTime changeDateField;

        private Document[] reasonField;

        /// <remarks/>
        public string CadNumber
        {
            get
            {
                return this.cadNumberField;
            }
            set
            {
                this.cadNumberField = value;
            }
        }

        /// <remarks/>
        public MLText ChangeName
        {
            get
            {
                return this.changeNameField;
            }
            set
            {
                this.changeNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime ChangeDate
        {
            get
            {
                return this.changeDateField;
            }
            set
            {
                this.changeDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Reason")]
        public Document[] Reason
        {
            get
            {
                return this.reasonField;
            }
            set
            {
                this.reasonField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://aisgzk.kz/integrations/v2019")]
    public partial class Document
    {

        private MLText nameField;

        private MLText issuedOgranField;

        private string seriesField;

        private string numberField;

        private System.Nullable<System.DateTime> issuedDateField;

        /// <remarks/>
        public MLText Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public MLText IssuedOgran
        {
            get
            {
                return this.issuedOgranField;
            }
            set
            {
                this.issuedOgranField = value;
            }
        }

        /// <remarks/>
        public string Series
        {
            get
            {
                return this.seriesField;
            }
            set
            {
                this.seriesField = value;
            }
        }

        /// <remarks/>
        public string Number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", IsNullable = true)]
        public System.Nullable<System.DateTime> IssuedDate
        {
            get
            {
                return this.issuedDateField;
            }
            set
            {
                this.issuedDateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://aisgzk.kz/integrations/v2019")]
    public partial class Bonitet
    {

        private double valueField;

        private System.DateTime bonDateField;

        private Soil[] soilField;

        /// <remarks/>
        public double Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime BonDate
        {
            get
            {
                return this.bonDateField;
            }
            set
            {
                this.bonDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Soil")]
        public Soil[] Soil
        {
            get
            {
                return this.soilField;
            }
            set
            {
                this.soilField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://aisgzk.kz/integrations/v2019")]
    public partial class Soil : AnyDictionary
    {

        private double squareField;

        private int yearField;

        private System.Nullable<double> bonitetField;

        /// <remarks/>
        public double Square
        {
            get
            {
                return this.squareField;
            }
            set
            {
                this.squareField = value;
            }
        }

        /// <remarks/>
        public int Year
        {
            get
            {
                return this.yearField;
            }
            set
            {
                this.yearField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<double> Bonitet
        {
            get
            {
                return this.bonitetField;
            }
            set
            {
                this.bonitetField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://aisgzk.kz/integrations/v2019")]
    public partial class Restrict
    {

        private MLText nameField;

        private System.DateTime startDateField;

        private System.Nullable<System.DateTime> stopDateField;

        private MLText validityField;

        private Document[] startReasonField;

        private Document[] stopReasonField;

        /// <remarks/>
        public MLText Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime StartDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                this.startDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", IsNullable = true)]
        public System.Nullable<System.DateTime> StopDate
        {
            get
            {
                return this.stopDateField;
            }
            set
            {
                this.stopDateField = value;
            }
        }

        /// <remarks/>
        public MLText Validity
        {
            get
            {
                return this.validityField;
            }
            set
            {
                this.validityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StartReason")]
        public Document[] StartReason
        {
            get
            {
                return this.startReasonField;
            }
            set
            {
                this.startReasonField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StopReason")]
        public Document[] StopReason
        {
            get
            {
                return this.stopReasonField;
            }
            set
            {
                this.stopReasonField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://aisgzk.kz/integrations/v2019")]
    public partial class GzkObject
    {

        private System.DateTime actualDateField;

        private string cadNumberField;

        private AnyDictionary addressField;

        private double squareField;

        private MLText purposeField;

        private MLText divisibleField;

        private Restrict[] restrictField;

        private EconomicChar[] economicCharField;

        private Bonitet bonitetField;

        private CadNumberHistory[] cadNumberHistoryField;

        private Right[] rightField;

        private GICoordinates coordinatesField;

        /// <remarks/>
        public System.DateTime ActualDate
        {
            get
            {
                return this.actualDateField;
            }
            set
            {
                this.actualDateField = value;
            }
        }

        /// <remarks/>
        public string CadNumber
        {
            get
            {
                return this.cadNumberField;
            }
            set
            {
                this.cadNumberField = value;
            }
        }

        /// <remarks/>
        public AnyDictionary Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }

        /// <remarks/>
        public double Square
        {
            get
            {
                return this.squareField;
            }
            set
            {
                this.squareField = value;
            }
        }

        /// <remarks/>
        public MLText Purpose
        {
            get
            {
                return this.purposeField;
            }
            set
            {
                this.purposeField = value;
            }
        }

        /// <remarks/>
        public MLText Divisible
        {
            get
            {
                return this.divisibleField;
            }
            set
            {
                this.divisibleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Restrict")]
        public Restrict[] Restrict
        {
            get
            {
                return this.restrictField;
            }
            set
            {
                this.restrictField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EconomicChar")]
        public EconomicChar[] EconomicChar
        {
            get
            {
                return this.economicCharField;
            }
            set
            {
                this.economicCharField = value;
            }
        }

        /// <remarks/>
        public Bonitet Bonitet
        {
            get
            {
                return this.bonitetField;
            }
            set
            {
                this.bonitetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CadNumberHistory")]
        public CadNumberHistory[] CadNumberHistory
        {
            get
            {
                return this.cadNumberHistoryField;
            }
            set
            {
                this.cadNumberHistoryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Right")]
        public Right[] Right
        {
            get
            {
                return this.rightField;
            }
            set
            {
                this.rightField = value;
            }
        }

        /// <remarks/>
        public GICoordinates Coordinates
        {
            get
            {
                return this.coordinatesField;
            }
            set
            {
                this.coordinatesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://aisgzk.kz/integrations/v2019")]
    public partial class EconomicChar : AnyDictionary
    {

        private double valueField;

        private System.DateTime startDateField;

        private Document reasonField;

        /// <remarks/>
        public double Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime StartDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                this.startDateField = value;
            }
        }

        /// <remarks/>
        public Document Reason
        {
            get
            {
                return this.reasonField;
            }
            set
            {
                this.reasonField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://aisgzk.kz/integrations/v2019")]
    public partial class Right : AnyDictionary
    {

        private string rightHolderIdField;

        private System.DateTime startDateField;

        private System.Nullable<System.DateTime> stopDatePlanField;

        private System.Nullable<System.DateTime> stopDateFactField;

        private MLText validityField;

        private MLText statusField;

        private ObjectPart partField;

        private Document[] startReasonField;

        private Document[] stopReasonField;

        private Document[] identityDocumentField;

        /// <remarks/>
        public string RightHolderId
        {
            get
            {
                return this.rightHolderIdField;
            }
            set
            {
                this.rightHolderIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime StartDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                this.startDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", IsNullable = true)]
        public System.Nullable<System.DateTime> StopDatePlan
        {
            get
            {
                return this.stopDatePlanField;
            }
            set
            {
                this.stopDatePlanField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", IsNullable = true)]
        public System.Nullable<System.DateTime> StopDateFact
        {
            get
            {
                return this.stopDateFactField;
            }
            set
            {
                this.stopDateFactField = value;
            }
        }

        /// <remarks/>
        public MLText Validity
        {
            get
            {
                return this.validityField;
            }
            set
            {
                this.validityField = value;
            }
        }

        /// <remarks/>
        public MLText Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        public ObjectPart Part
        {
            get
            {
                return this.partField;
            }
            set
            {
                this.partField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StartReason")]
        public Document[] StartReason
        {
            get
            {
                return this.startReasonField;
            }
            set
            {
                this.startReasonField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StopReason")]
        public Document[] StopReason
        {
            get
            {
                return this.stopReasonField;
            }
            set
            {
                this.stopReasonField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IdentityDocument")]
        public Document[] IdentityDocument
        {
            get
            {
                return this.identityDocumentField;
            }
            set
            {
                this.identityDocumentField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://aisgzk.kz/integrations/v2019")]
    public partial class ObjectPart : AnyDictionary
    {

        private string partNumberField;

        private MLText purposeField;

        private double squareField;

        /// <remarks/>
        public string PartNumber
        {
            get
            {
                return this.partNumberField;
            }
            set
            {
                this.partNumberField = value;
            }
        }

        /// <remarks/>
        public MLText Purpose
        {
            get
            {
                return this.purposeField;
            }
            set
            {
                this.purposeField = value;
            }
        }

        /// <remarks/>
        public double Square
        {
            get
            {
                return this.squareField;
            }
            set
            {
                this.squareField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://aisgzk.kz/integrations/v2019")]
    public partial class GICoordinates
    {

        private GIRing[] oldGeometryField;

        private GIRing[] newGeometryField;

        private string spatialReferenceField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OldGeometry")]
        public GIRing[] OldGeometry
        {
            get
            {
                return this.oldGeometryField;
            }
            set
            {
                this.oldGeometryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NewGeometry")]
        public GIRing[] NewGeometry
        {
            get
            {
                return this.newGeometryField;
            }
            set
            {
                this.newGeometryField = value;
            }
        }

        /// <remarks/>
        public string SpatialReference
        {
            get
            {
                return this.spatialReferenceField;
            }
            set
            {
                this.spatialReferenceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://aisgzk.kz/integrations/v2019")]
    public partial class GIRing
    {

        private int numberField;

        private GIVertex[] vertexesField;

        /// <remarks/>
        public int Number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Vertexes")]
        public GIVertex[] Vertexes
        {
            get
            {
                return this.vertexesField;
            }
            set
            {
                this.vertexesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://aisgzk.kz/integrations/v2019")]
    public partial class GIVertex
    {

        private int numberField;

        private string xField;

        private string yField;

        private System.Nullable<double> measureField;

        /// <remarks/>
        public int Number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }

        /// <remarks/>
        public string X
        {
            get
            {
                return this.xField;
            }
            set
            {
                this.xField = value;
            }
        }

        /// <remarks/>
        public string Y
        {
            get
            {
                return this.yField;
            }
            set
            {
                this.yField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<double> Measure
        {
            get
            {
                return this.measureField;
            }
            set
            {
                this.measureField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://aisgzk.kz/integrations/v2019")]
    public partial class GISemanticItem
    {

        private string elementNameField;

        private string elementValueField;

        /// <remarks/>
        public string ElementName
        {
            get
            {
                return this.elementNameField;
            }
            set
            {
                this.elementNameField = value;
            }
        }

        /// <remarks/>
        public string ElementValue
        {
            get
            {
                return this.elementValueField;
            }
            set
            {
                this.elementValueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://aisgzk.kz/integrations/v2019")]
    public partial class GIItem
    {

        private System.DateTime actualDateField;

        private GISemanticItem[] semanticDataField;

        private GICoordinates geometryField;

        private GzkObject gzkObjectField;

        /// <remarks/>
        public System.DateTime ActualDate
        {
            get
            {
                return this.actualDateField;
            }
            set
            {
                this.actualDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SemanticData")]
        public GISemanticItem[] SemanticData
        {
            get
            {
                return this.semanticDataField;
            }
            set
            {
                this.semanticDataField = value;
            }
        }

        /// <remarks/>
        public GICoordinates Geometry
        {
            get
            {
                return this.geometryField;
            }
            set
            {
                this.geometryField = value;
            }
        }

        /// <remarks/>
        public GzkObject GzkObject
        {
            get
            {
                return this.gzkObjectField;
            }
            set
            {
                this.gzkObjectField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://aisgzk.kz/integrations/v2019")]
    public partial class GIRelevanceInfo : AnyDictionary
    {

        private System.DateTime dateActField;

        private GIType geometryTypeField;

        private AnyDictionary territoryField;

        /// <remarks/>
        public System.DateTime DateAct
        {
            get
            {
                return this.dateActField;
            }
            set
            {
                this.dateActField = value;
            }
        }

        /// <remarks/>
        public GIType GeometryType
        {
            get
            {
                return this.geometryTypeField;
            }
            set
            {
                this.geometryTypeField = value;
            }
        }

        /// <remarks/>
        public AnyDictionary Territory
        {
            get
            {
                return this.territoryField;
            }
            set
            {
                this.territoryField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://aisgzk.kz/integrations/v2019")]
    public enum GIType
    {

        /// <remarks/>
        unknown,

        /// <remarks/>
        point,

        /// <remarks/>
        polyline,

        /// <remarks/>
        polygon,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://aisgzk.kz/integrations/v2019")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://aisgzk.kz/integrations/v2019", IsNullable = true)]
    public partial class GIDataRequest
    {

        private string layerNameField;

        private string requestUserField;

        /// <remarks/>
        public string LayerName
        {
            get
            {
                return this.layerNameField;
            }
            set
            {
                this.layerNameField = value;
            }
        }

        /// <remarks/>
        public string RequestUser
        {
            get
            {
                return this.requestUserField;
            }
            set
            {
                this.requestUserField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://aisgzk.kz/integrations/v2019")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://aisgzk.kz/integrations/v2019", IsNullable = true)]
    public partial class GIRelevanceResponse
    {

        private GIRelevanceInfo[] availableInfoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AvailableInfo")]
        public GIRelevanceInfo[] AvailableInfo
        {
            get
            {
                return this.availableInfoField;
            }
            set
            {
                this.availableInfoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://aisgzk.kz/integrations/v2019")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://aisgzk.kz/integrations/v2019", IsNullable = true)]
    public partial class GIRelevanceRequest
    {

        private string requestUserField;

        /// <remarks/>
        public string RequestUser
        {
            get
            {
                return this.requestUserField;
            }
            set
            {
                this.requestUserField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://aisgzk.kz/integrations/v2019")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://aisgzk.kz/integrations/v2019", IsNullable = true)]
    public partial class GISendActualDataResponse
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://aisgzk.kz/integrations/v2019")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://aisgzk.kz/integrations/v2019", IsNullable = true)]
    public partial class GISendActualDataRequest : GISendDataRequest
    {

        private AnyDictionary layerInfoField;

        /// <remarks/>
        public AnyDictionary LayerInfo
        {
            get
            {
                return this.layerInfoField;
            }
            set
            {
                this.layerInfoField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GISendActualDataRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://aisgzk.kz/integrations/v2019")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://aisgzk.kz/integrations/v2019", IsNullable = true)]
    public partial class GISendDataRequest
    {

        private string pushIdField;

        private string fromUserField;

        private bool pushFinishField;

        private byte[] binaryDataField;

        private GIItem[] dataField;

        /// <remarks/>
        public string PushId
        {
            get
            {
                return this.pushIdField;
            }
            set
            {
                this.pushIdField = value;
            }
        }

        /// <remarks/>
        public string FromUser
        {
            get
            {
                return this.fromUserField;
            }
            set
            {
                this.fromUserField = value;
            }
        }

        /// <remarks/>
        public bool PushFinish
        {
            get
            {
                return this.pushFinishField;
            }
            set
            {
                this.pushFinishField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")]
        public byte[] BinaryData
        {
            get
            {
                return this.binaryDataField;
            }
            set
            {
                this.binaryDataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Data")]
        public GIItem[] Data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://aisgzk.kz/integrations/v2019")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://aisgzk.kz/integrations/v2019", IsNullable = true)]
    public partial class GISendDataResponse
    {
    }
}